# Generated by Django 2.1 on 2019-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='name_text',
            field=models.CharField(default='jane', max_length=50),
        ),
    ]
