# Generated by Django 2.1 on 2019-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_bmi_name_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
